
Anikeit Sethi
(190001003)

# Q1. Auto Associative Neural Network

In [37]:
import numpy as np


tar = np.array([
    
    [1,1,1,1],
    
    [1,1,-1,-1]
   
    ]
)

class Hopfield_Net:

    def __init__(self):
        self.wei= np.dot (tar.T, tar)
        for i in range(len(self.wei)):
                self.wei[i][i]=0;
        self.thresh=0        
        print("weights(W4x4) are:\n",self.wei)
   
    #Threshold
    # 3 cases
        # asynch learning ## IMPORTANT
        # y_itr is updating, y is prev value
    def check_thresh(self, y_in, y):
        output=y
        if(y_in>self.thresh):
            output=1
        elif(y_in<self.thresh):
            output=0
      #  print(output,'output')
        return output
    
    def parse(self, matrix_inp):
        for x in matrix_inp:
            y=x
            y_in=y#3rd case
            order = [1,4,3,2]
            iter=0
            while True:
                temp = list(y)
                for i in order:
                    sum=0
                    c=0
                    for row in self.wei:
                        sum+=y[c]*row[i-1]
                        c=c+1
                    y_in[i-1]=x[i-1] + sum
                    y[i-1]=self.check_thresh(y_in[i-1], y[i-1]) 
                
                
                if np.array_equal(y,temp):
                    break
                iter+=1
            
            #for k in range(0,j):
            print("\noutput for test cases====", y)    
            print(iter)                   

In [39]:
print("------------------------------")
matrix_inp = np.array([[1,1,1,1],#test_cases
                       [1,1,-1,-1],
                       [1,1,1,0]])

j = len(matrix_inp)-1
#print(j)
h_model=Hopfield_Net()
h_model.parse(matrix_inp)

------------------------------
weights(W4x4) are:
 [[0 2 0 0]
 [2 0 0 0]
 [0 0 0 2]
 [0 0 2 0]]

output for test cases==== [1 1 1 1]
0

output for test cases==== [1 1 0 0]
1

output for test cases==== [1 1 1 1]
1
